/* Responsive-image helper. Builds AVIF + WebP srcset strings pointing at the
 * width variants pre-generated by scripts/gen-image-variants.mjs, so card and
 * banner photos render right-sized in a modern format instead of shipping the
 * full 900-1000px source (PageSpeed "Improve image delivery").
 *
 * Used inline (not as a wrapper component) so each <img> stays in its parent's
 * Astro style scope — the existing `.about-card img` / `.ev-media img` rules keep
 * applying unchanged. The original `src` remains the <picture> fallback, so a
 * missing variant just degrades to the unoptimised original. */

/** ~280px card slots (About evolution, R32 gallery): DPR1 + retina. */
export const CARD_WIDTHS = [400, 700];
/** Event banners: ~390px in cards, up to ~900px on the detail hero. */
export const BANNER_WIDTHS = [450, 900];

export function variants(src: string, widths: number[]): { avif: string; webp: string } {
  const base = src.replace(/\.[^.]+$/, '');
  const set = (ext: string) => widths.map((w) => `${base}-${w}.${ext} ${w}w`).join(', ');
  return { avif: set('avif'), webp: set('webp') };
}
