// Contract 4: BLG. Renders BabyLoveGrowth-shaped fixture posts through the real
// templates and asserts on the result.
//
// The site renders from src/data/articles.generated.ts at build time, so the
// contract builds a scratch COPY of the repo whose generated file is replaced
// by (existing articles + fixtures run through the real normalizeArticle). No
// production code, data path or vendor payload handling is touched: the seam is
// "a different copy of the repo", nothing in src/ knows about it.

import { spawnSync } from 'node:child_process';
import {
  cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { ACCEPTED, REJECTED, STRIPPED_MARKERS, TEXT_KEPT_MARKERS } from '../blog-fixtures.mjs';
import { CANONICAL_ORIGIN, DEFAULT_LOCALE, LOCALES } from '../lib/constants.mjs';
import { loadDist } from '../lib/dist.mjs';
import { startServer } from '../lib/server.mjs';

const C = 'blog';
const HERO_WIDTHS = [400, 640, 800, 1280];
const FORBIDDEN_TAGS = ['script', 'iframe', 'form', 'object', 'embed', 'style', 'svg', 'video', 'audio', 'input', 'button', 'link', 'meta', 'canvas', 'h1'];
const CHROME_CANDIDATES = ['/opt/pw-browsers/chromium', '/usr/bin/google-chrome', '/usr/bin/chromium', '/usr/bin/chromium-browser'];

/** Run every fixture through the real normalizer, exactly as the sync does. */
export async function normalizeFixtures(repoRoot) {
  const { normalizeArticle } = await import(pathToFileURL(join(repoRoot, 'scripts/articles-sync/normalize.mjs')).href);
  const context = { locales: LOCALES, canonicalOrigin: CANONICAL_ORIGIN, bareHosts: ['sisiwroclaw.pl'] };
  const accepted = [];
  const problems = [];
  for (const fixture of ACCEPTED) {
    const { article, errors, warnings } = normalizeArticle(fixture.payload, context);
    if (!article) problems.push(`${fixture.payload.slug}: normalizer rejected an accepted fixture (${errors.join('; ')})`);
    else accepted.push({ ...fixture, article, warnings });
  }
  const rejected = REJECTED.map((fixture) => {
    const { article, errors } = normalizeArticle(fixture.payload, context);
    return { ...fixture, article, errors, slug: fixture.payload.slug };
  });
  return { accepted, rejected, problems };
}

/** Hero variants for a fixture, written like scripts/sync-articles.mjs names them. */
async function writeHero(scratch, article, index) {
  const sharp = (await import('sharp')).default;
  const dir = join(scratch, 'public', 'blog');
  mkdirSync(dir, { recursive: true });
  const base = `${article.locale}-${article.slug}`;
  const shade = 40 + index * 25;
  const source = await sharp({ create: { width: 1280, height: 720, channels: 3, background: { r: shade, g: 8, b: 30 } } }).png().toBuffer();
  const variants = [];
  for (const width of HERO_WIDTHS) {
    const out = await sharp(source).resize({ width }).webp({ quality: 40 }).toBuffer({ resolveWithObject: true });
    const name = `${base}-${out.info.width}.webp`;
    writeFileSync(join(dir, name), out.data);
    variants.push({ name, width: out.info.width, height: out.info.height });
  }
  const widest = variants.at(-1);
  return {
    img: `/blog/${widest.name}`,
    imgSrcset: variants.map((v) => `/blog/${v.name} ${v.width}w`).join(', '),
    imgWidth: widest.width,
    imgHeight: widest.height,
  };
}

function existingArticles(repoRoot) {
  const source = readFileSync(join(repoRoot, 'src/data/articles.generated.ts'), 'utf8');
  const start = source.indexOf('= [');
  const end = source.lastIndexOf('];');
  return JSON.parse(source.slice(start + 2, end + 1));
}

function renderModule(articles) {
  return (
    '// GENERATED by scripts/contract (scratch copy). Not the repo file.\n' +
    "import type { ArticleItem } from './articles';\n\n" +
    `export const GENERATED_ARTICLES: ArticleItem[] = ${JSON.stringify(articles, null, 2)};\n`
  );
}

/** Copy the repo (minus node_modules, dist, .git) into a temp folder and swap in the fixture data. */
export async function prepareScratch(repoRoot, fixtures) {
  const scratch = mkdtempSync(join(tmpdir(), 'sisi-contract-blg-'));
  for (const entry of ['src', 'public', 'scripts', 'astro.config.mjs', 'tsconfig.json', 'package.json']) {
    cpSync(join(repoRoot, entry), join(scratch, entry), { recursive: true });
  }
  symlinkSync(join(repoRoot, 'node_modules'), join(scratch, 'node_modules'), 'dir');

  const withHero = [];
  let index = 0;
  for (const fixture of fixtures.accepted) {
    const article = { ...fixture.article };
    if (article.heroSource) Object.assign(article, await writeHero(scratch, article, index));
    index += 1;
    withHero.push(article);
    fixture.published = article;
  }
  const all = [...existingArticles(repoRoot), ...withHero]
    .sort((a, b) => b.publishedAt.localeCompare(a.publishedAt) || a.slug.localeCompare(b.slug));
  writeFileSync(join(scratch, 'src/data/articles.generated.ts'), renderModule(all));
  return scratch;
}

function buildScratch(repoRoot, scratch) {
  const astro = join(repoRoot, 'node_modules/astro/bin/astro.mjs');
  const env = { ...process.env, CONTEXT: 'production', URL: CANONICAL_ORIGIN, ASTRO_TELEMETRY_DISABLED: '1', NO_COLOR: '1' };
  const build = spawnSync(process.execPath, [astro, 'build'], { cwd: scratch, env, encoding: 'utf8' });
  if (build.status !== 0) return { ok: false, log: `${build.stdout}\n${build.stderr}` };
  const headers = spawnSync(process.execPath, ['scripts/generate-headers.mjs'], { cwd: scratch, env, encoding: 'utf8' });
  if (headers.status !== 0) return { ok: false, log: `${headers.stdout}\n${headers.stderr}` };
  return { ok: true, log: '' };
}

const pathFor = (article) => `/${article.locale}/blog/${article.slug}/`;

export async function runBlogContract(ctx) {
  const { report, repoRoot, opts } = ctx;
  const fixtures = await normalizeFixtures(repoRoot);
  for (const message of fixtures.problems) report.fail(C, { field: 'fixture', message });
  report.pass(C, fixtures.accepted.length);

  // Bad-row policy: the normalizer must keep skipping these.
  for (const row of fixtures.rejected) {
    report.check(C, row.article === null, { url: row.slug, field: 'bad-row policy', message: `${row.reason}: the normalizer now accepts a row it must skip` });
  }

  const scratch = await prepareScratch(repoRoot, fixtures);
  let server;
  try {
    const built = buildScratch(repoRoot, scratch);
    if (!built.ok) {
      report.fail(C, { field: 'scratch build', message: `astro build of the fixture copy failed:\n${built.log.slice(-1500)}` });
      return;
    }
    const dist = join(scratch, 'dist');
    const model = loadDist(dist);
    server = await startServer(dist);
    await assertFixtures({ ctx, model, server, fixtures, dist });
    await assertLayout({ ctx, model, server, fixtures });
  } finally {
    await server?.close();
    if (opts.keepScratch) report.note(C, { message: `scratch build kept at ${scratch}` });
    else rmSync(scratch, { recursive: true, force: true });
  }
}

async function assertFixtures({ ctx, model, server, fixtures, dist }) {
  const { report } = ctx;
  const sitemap = new Map(model.sitemap.map((e) => [e.path, e]));
  const rawHtml = (path) => readFileSync(join(dist, path.replace(/^\//, ''), 'index.html'), 'utf8');

  for (const fixture of fixtures.accepted) {
    const article = fixture.published;
    const path = pathFor(article);
    const abs = CANONICAL_ORIGIN + path;
    const expect = fixture.expect;
    const ck = (ok, field, message) => report.check(C, ok, { url: path, field, message });
    const res = await server.head(path);
    ck(res.status === 200, 'render', `fixture page answers HTTP ${res.status}`);
    const page = model.pages.get(path);
    if (!page) continue;

    ck(page.h1.length === 1 && page.h1[0] === article.title, 'h1', `expected exactly one h1 "${article.title.slice(0, 40)}...", found ${JSON.stringify(page.h1).slice(0, 120)}`);
    ck(page.canonical === abs, 'canonical', `canonical ${page.canonical}, expected ${abs}`);
    ck(page.lang === article.locale, 'lang', `<html lang="${page.lang}">`);
    ck(/^index, follow/.test(page.robots ?? ''), 'robots', `robots "${page.robots}" on a production-context build`);

    const locales = [article.locale, ...(expect.translatedTo ?? [])].sort((a, b) => LOCALES.indexOf(a) - LOCALES.indexOf(b));
    const wantHreflang = Object.fromEntries(locales.map((l) => [l, `${CANONICAL_ORIGIN}/${l}/blog/${article.slug}/`]));
    if (locales.includes(DEFAULT_LOCALE)) wantHreflang['x-default'] = wantHreflang[DEFAULT_LOCALE];
    ck(JSON.stringify(Object.entries(page.hreflang).sort()) === JSON.stringify(Object.entries(wantHreflang).sort()), 'hreflang',
      `hreflang ${JSON.stringify(page.hreflang)} differs from ${JSON.stringify(wantHreflang)}`);

    const types = page.jsonLd.types;
    ck(types.includes('BlogPosting'), 'jsonld', 'BlogPosting missing');
    ck(types.includes('BreadcrumbList'), 'jsonld', 'BreadcrumbList missing');
    ck(types.includes('FAQPage') === (expect.faq > 0), 'jsonld', expect.faq > 0 ? 'FAQPage missing although the payload has FAQ entries' : 'FAQPage present without FAQ entries');
    ck(page.jsonLd.ids.includes(`${abs}#article`), 'jsonld', `no BlogPosting @id ${abs}#article`);
    ck(page.article?.faqItems === expect.faq, 'faq', `rendered ${page.article?.faqItems} FAQ item(s), expected ${expect.faq}`);
    ck(page.og['og:type'] === 'article' && Boolean(page.og['article:published_time']), 'og', 'og:type article / article:published_time missing');

    if (expect.hero) {
      ck(page.hasHero && page.og['og:image'] === CANONICAL_ORIGIN + article.img && model.exists(article.img), 'hero', `hero/og:image ${page.og['og:image']} does not resolve to ${article.img}`);
      ck(!page.article.imgs.some((i) => i.src === article.heroSource), 'hero', 'the vendor hero is repeated in the body instead of being dropped');
    } else {
      ck(!page.hasHero, 'hero', 'a hero block rendered for an article without hero_image_url');
      ck(Boolean(page.og['og:image']), 'og:image', 'no og:image fallback for an article without a hero');
    }
    if (expect.keywords) ck(rawHtml(path).includes('"keywords":"'), 'keywords', 'vendor keywords not carried into BlogPosting');

    // Sanitised body.
    const body = page.article;
    ck(Boolean(body), 'body', '.ba-body not found');
    if (body) {
      for (const tag of FORBIDDEN_TAGS) ck(!body.tags[tag], 'sanitiser', `<${tag}> survived in the article body (${body.tags[tag]}x)`);
      ck(body.eventAttrs === 0 && body.styleAttrs === 0 && body.jsHrefs === 0, 'sanitiser', `event handlers ${body.eventAttrs}, style attrs ${body.styleAttrs}, javascript: hrefs ${body.jsHrefs}`);
      ck(body.text.length > 300, 'body', 'article body text is nearly empty');
    }
    const html = rawHtml(path);
    for (const marker of STRIPPED_MARKERS) ck(!html.includes(marker), 'sanitiser', `stripped content "${marker}" appears in the built page`);
    const kept = TEXT_KEPT_MARKERS.filter((marker) => html.includes(marker));
    if (kept.length) report.note(C, { url: path, field: 'sanitiser', message: `object/video/form/button tags were dropped but their inner text was kept as plain text (${kept.join(', ')}); docs/BLOG.md says these are dropped with their content` });
    if (expect.stress) {
      ck(body.tags.table >= 1 && body.tags.blockquote >= 2 && body.tags.ol >= 1 && body.tags.ul >= 3, 'stress', 'table / blockquote / nested list markup was lost');
      ck(body.headings.every((h) => h.level >= 2), 'stress', 'an h1 survived inside the body');
      ck(body.text.includes('zażółć gęślą jaźń') && body.text.includes('日本語') && body.text.includes('příliš žluťoučký kůň'), 'unicode', 'diacritics or non-latin text did not survive');
      const noAlt = body.imgs.filter((i) => i.alt === null || i.alt === '').length;
      if (noAlt) report.note(C, { url: path, field: 'a11y', message: `${noAlt} body image(s) render without alt text; the sanitiser passes a missing alt through` });
    }
    if (expect.locale === 'pl' && !expect.camel && !expect.stress && !expect.longTokens) ck(body.text.includes('Zażółć') || article.slug.includes('no-hero'), 'unicode', 'Polish diacritics missing from the body');

    // Sitemap and hub.
    const sm = sitemap.get(path);
    ck(Boolean(sm), 'sitemap', 'fixture URL is not in sitemap.xml');
    if (sm) ck(JSON.stringify(Object.entries(sm.alternates).sort()) === JSON.stringify(Object.entries(wantHreflang).sort()), 'sitemap', `sitemap alternates ${Object.keys(sm.alternates)} differ from page hreflang ${Object.keys(wantHreflang)}`);
    const hub = model.pages.get(`/${article.locale}/blog/`);
    ck(Boolean(hub) && hub.links.some((l) => l.tag === 'a' && l.url === path), 'hub', `blog hub /${article.locale}/blog/ has no link to the article`);
    ck(sitemap.has(`/${article.locale}/blog/`) && /^index, follow/.test(hub?.robots ?? ''), 'hub', `blog hub /${article.locale}/blog/ is not indexable / in the sitemap`);
    ck(Boolean(hub?.jsonLd.types.includes('Blog')), 'hub', 'blog hub has no Blog JSON-LD');
    ck((model.llmsFull ?? '').includes(article.title) === (article.locale === DEFAULT_LOCALE), 'llms-full', article.locale === DEFAULT_LOCALE ? 'Polish fixture missing from llms-full.txt' : 'non-Polish fixture leaked into llms-full.txt');
  }

  // Skipped rows never appear.
  for (const row of fixtures.rejected) {
    const path = `/pl/blog/${row.slug}/`;
    report.check(C, !model.pages.has(path) && !sitemap.has(path), { url: path, field: 'bad-row policy', message: `${row.reason}: a skipped row was published` });
  }
  // The x-default rule on the en hub: pl is in the set, so the default points at pl.
  const enHub = model.pages.get('/en/blog/');
  report.check(C, enHub?.hreflang['x-default'] === `${CANONICAL_ORIGIN}/pl/blog/`, { url: '/en/blog/', field: 'hreflang', message: `en hub x-default is ${enHub?.hreflang['x-default']}` });
}

async function assertLayout({ ctx, model, server, fixtures }) {
  const { report, opts } = ctx;
  if (opts.noBrowser) {
    report.unverified(C, { field: '375px overflow', message: 'skipped by --no-browser' });
    return;
  }
  const executablePath = [process.env.CHROME_PATH, ...CHROME_CANDIDATES].find((p) => p && existsSync(p));
  if (!executablePath) {
    report.fail(C, { field: '375px overflow', message: `no Chromium found (tried CHROME_PATH and ${CHROME_CANDIDATES.join(', ')}); pass --no-browser to skip` });
    return;
  }
  const { chromium } = await import('playwright-core');
  const browser = await chromium.launch({ executablePath, headless: true, args: ['--no-sandbox'] });
  const blocked = new Set();
  try {
    const context = await browser.newContext({ viewport: { width: 375, height: 812 }, deviceScaleFactor: 1 });
    // Nothing leaves the machine: only the local dist server is reachable.
    await context.route('**/*', (route) => {
      const url = route.request().url();
      if (url.startsWith(server.base) || url.startsWith('data:') || url.startsWith('blob:')) return route.continue();
      blocked.add(new URL(url).host);
      return route.abort('blockedbyclient');
    });
    const targets = [...fixtures.accepted.map((f) => pathFor(f.published)), '/pl/blog/', '/en/blog/'];
    for (const path of targets) {
      const page = await context.newPage();
      try {
        const response = await page.goto(server.base + path, { waitUntil: 'load', timeout: 20000 });
        await page.evaluate(() => document.fonts.ready);
        await page.waitForTimeout(400);
        const metrics = await page.evaluate(measureOverflow);
        report.check(C, response?.status() === 200, { url: path, field: '375px render', message: `HTTP ${response?.status()}` });
        report.check(C, metrics.scrollWidth <= metrics.viewport, {
          url: path, field: '375px overflow',
          message: `page scrolls horizontally: scrollWidth ${metrics.scrollWidth} > ${metrics.viewport}. Overflowing elements: ${metrics.kinds.join(', ')}; widest ${metrics.offenders.slice(0, 2).map((o) => `${o.node} right=${o.right}`).join('; ')}`,
        });
        report.check(C, metrics.clipped.length === 0, {
          url: path, field: '375px clipped content',
          message: `content is wider than the viewport but hidden by overflow:hidden on the page: ${metrics.clipped.map((o) => `${o.node} right=${o.right}`).join('; ')}`,
        });
      } finally {
        await page.close();
      }
    }
    report.note(C, { field: 'network', message: `browser requests blocked (never sent): ${blocked.size ? [...blocked].join(', ') : 'none'}` });
  } finally {
    await browser.close();
  }
  void model;
}

/** Runs in the browser. Kept self-contained: it is serialised into the page. */
function measureOverflow() {
  const vw = window.innerWidth;
  const doc = document.documentElement;
  const scrollWidth = Math.max(doc.scrollWidth, document.body.scrollWidth);
  const label = (el) => `${el.tagName.toLowerCase()}${el.className && typeof el.className === 'string' ? `.${el.className.split(/\s+/)[0]}` : ''}`;
  const clippedByAncestor = (el) => {
    for (let p = el.parentElement; p && p !== document.body && p !== doc; p = p.parentElement) {
      const ox = getComputedStyle(p).overflowX;
      if (ox === 'auto' || ox === 'scroll' || ox === 'clip' || (ox === 'hidden' && p.getBoundingClientRect().right <= vw + 1)) return true;
    }
    return false;
  };
  const all = [...document.querySelectorAll('main *')];
  // A block whose text is wider than the block keeps its own box width, so the
  // box test alone misses it: also compare scrollWidth with clientWidth.
  const wide = all
    .map((el) => {
      const rect = el.getBoundingClientRect();
      const textOverflow = getComputedStyle(el).overflowX === 'visible' && el.scrollWidth > el.clientWidth + 1 && el.clientWidth > 0;
      return { el, right: Math.round(Math.max(rect.right, textOverflow ? rect.left + el.scrollWidth : 0)) };
    })
    .filter(({ el, right }) => right > vw + 1 && el.getBoundingClientRect().width > 0 && getComputedStyle(el).position !== 'fixed');
  const offenders = wide.filter(({ el }) => !clippedByAncestor(el)).sort((a, b) => b.right - a.right);
  const kinds = [...new Set(offenders.map(({ el }) => label(el)))].slice(0, 8);
  const bodyOverflowHidden = getComputedStyle(document.body).overflowX === 'hidden' || getComputedStyle(doc).overflowX === 'hidden';
  return {
    viewport: vw,
    scrollWidth,
    offenders: offenders.slice(0, 6).map(({ el, right }) => ({ node: label(el), right })),
    kinds,
    clipped: scrollWidth <= vw && bodyOverflowHidden ? offenders.map(({ el, right }) => ({ node: label(el), right })) : [],
  };
}
