/* Venue truth: the gap log, as data.

   One row per fact the site needs and no source provides (`missing`), or per
   fact where two places in the repo disagree and the owner has to pick
   (`decision`). venue.ts points at a row with `gap('ID')`; the row supplies the
   placeholder text. `scripts/venue-export.mjs --gaps-md` turns this table into
   docs/sisi-elevate/GAPS.md, so the document cannot drift from the code.

   Every row is PENDING. Nothing here is filled in by guessing. Evidence is a
   `file:line` at repo commit f8ccc58 that shows the absence or the conflict. */

import type { GapId, GapRow } from './types';

export const GAPS: Record<GapId, GapRow> = {
  LINEUP: {
    id: 'LINEUP',
    kind: 'missing',
    what: 'The lineup for each coming night: which acts and DJs play.',
    why: 'A guest deciding whether tonight or this weekend is worth going out cannot tell what will be playing.',
    where: 'Home "Nadchodzące wydarzenia", the events hub, each event page, Event JSON-LD (performer).',
    owner: 'Ignacy, with whoever books the nights; the pipeline is the Drive folder "Wydarzenia".',
    placeholder: '[LINEUP?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: [
      'src/data/events.generated.ts:5 (GENERATED_EVENTS is an empty array)',
      'src/data/site.ts:59-63 (lineup is authored in Drive, never in the repo)',
    ],
    notes: 'The build has 0 event pages (RESEARCH.md), so the events hub is noindex and out of the nav.',
  },
  ARTISTS: {
    id: 'ARTISTS',
    kind: 'missing',
    what: 'Names of the resident DJs, live acts and guests.',
    why: 'A guest judging whether the music fits their taste has no name to look up or listen to.',
    where: 'Event cards and pages, the home "Live Acty" and "Friday Session" copy, the events hub.',
    owner: 'Ignacy and the bookers. Real names only, with the artist\'s permission to be named.',
    placeholder: '[ARTIST?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: [
      'src/i18n/ui/pl.ts:157-161 (the About cards say "Friday Session" and "Live Acty" and name nobody)',
      'src/data/home-night.ts:20-22 (live acts and DJs described as phases of the night, no names)',
    ],
  },
  EVENT_DATES: {
    id: 'EVENT_DATES',
    kind: 'missing',
    what: 'Dates, start times and entry price of the coming events.',
    why: 'A guest cannot pick a night or budget for the door when no event is dated.',
    where: 'Events hub, event pages, home events strip, Event JSON-LD (startDate, offers).',
    owner: 'Ignacy (Drive folder "Wydarzenia").',
    placeholder: '[DATE?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/data/events.generated.ts:5'],
  },
  DJ_START: {
    id: 'DJ_START',
    kind: 'missing',
    what: 'The time the live set ends and the DJs start.',
    why: 'A guest who wants the live music, or only the dance floor, cannot choose when to arrive within the 22:00-23:00 window.',
    where: 'Home "night" phases, event pages, the reservations page.',
    owner: 'Ignacy / the night manager.',
    placeholder: '[DJ-START?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: [
      'src/data/home-night.ts:13-14 (the file states these are phases of a night, not scheduled times)',
      'src/data/home-night.ts:21-22',
    ],
  },
  ALLERGENS: {
    id: 'ALLERGENS',
    kind: 'missing',
    what: 'Allergen information for every drink and every dish.',
    why: 'A guest with an allergy cannot check what is safe to order. Today they would have to ask staff.',
    where: 'Menu page (each row), The Cork dishes, the home Night Menu tab.',
    owner: 'The Cork kitchen lead and the bar manager; Ignacy signs off the final list.',
    placeholder: '[ALLERGENS?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: [
      'src/data/bar-menu.ts:11 (the Item type has no allergen field)',
      'src/data/food-menu.ts:9 (the Dish type has no allergen field)',
      'src/data/bar-menu.ts:163-164 (Egg White is listed as an ingredient of two cocktails; nothing else is flagged)',
    ],
  },
  ABV: {
    id: 'ABV',
    kind: 'missing',
    what: 'Alcohol by volume for each drink. Only the 8 beers state it, in their description text.',
    why: 'A guest pacing themselves or choosing a lighter drink cannot compare strengths.',
    where: 'Menu page rows and the home menu preview.',
    owner: 'The bar manager, from the labels or the distributor sheets.',
    placeholder: '[ABV?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: [
      'src/data/bar-menu.ts:349-351 (draught: 5%, 4.9%, 6.5%)',
      'src/data/bar-menu.ts:355-359 (bottled: 4.5%, 0%, Blonde 6.6% / Brune 6.5%, 5%, 5%)',
    ],
    notes:
      'The beer figures are recorded as PENDING facts with their source. Leffe Blonde is 6.5% on draught (line 351) and 6.6% in the bottle (line 357): both kept, neither chosen.',
  },
  TASTE_TAGS: {
    id: 'TASTE_TAGS',
    kind: 'missing',
    what: 'Taste tags per drink (for example dry, sweet, bitter, citrus, smoky).',
    why: 'A guest who does not know spirits cannot choose a drink by taste or ask for "something like" one they know.',
    where: 'Menu page (filter or chips), home menu preview, any drink finder.',
    owner: 'The bar manager. Tags must come from the bar, not from a guess at the recipe.',
    placeholder: '[TAGS?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/data/bar-menu.ts:11 (no tag field)'],
  },
  DISH_PRICE: {
    id: 'DISH_PRICE',
    kind: 'missing',
    what: 'Crostini has no price on the site.',
    why: 'A guest ordering food from the Night Menu sees a dish they cannot cost.',
    where: 'Menu page, The Cork block.',
    owner: 'The Cork kitchen lead.',
    placeholder: '[PRICE?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/data/food-menu.ts:86-97 (Crostini has `tiers: []`)', 'src/components/FoodMenu.astro:46 (prices render only when a tier exists)'],
  },
  FOOD_MENU: {
    id: 'FOOD_MENU',
    kind: 'missing',
    what:
      'Whether the food menu is complete. The site shows 9 dishes in 2 sections (7 "Na początek", 2 "Na ciepło"); 8 have a price. The home Night Menu tab shows 3. No sides, desserts, weights, or kitchen hours are shown, and only 1 dish is marked vegetarian and 2 spicy.',
    why: 'A guest planning dinner before the club, or a vegetarian guest, cannot tell if this is the whole offer.',
    where: 'Menu page (The Cork block), home Night Menu tab, llms.txt.',
    owner: 'The Cork kitchen lead, then Ignacy.',
    placeholder: '[MENU?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: [
      'src/data/food-menu.ts:69-229 (SECTIONS: 7 + 2 dishes)',
      'src/data/food-menu.ts:32-33 (comment: only the cheese board is marked; the rest await the kitchen\'s list)',
      'src/components/home/MenuTeaser.astro:31 (the home tab picks 3 dishes)',
    ],
    notes: 'The count is from the source and the local build (dist/pl/menu/index.html has 9 `food-item` blocks).',
  },
  THE_CORK_HOURS: {
    id: 'THE_CORK_HOURS',
    kind: 'missing',
    what: 'Opening hours of the restaurant The Cork, including weekdays and kitchen closing time.',
    why: 'A guest planning dinner before the club cannot tell when The Cork is open.',
    where: 'Home R32 block, menu page food section, contact page.',
    owner: 'Ignacy / The Cork manager.',
    placeholder: '[CORK-HOURS?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: [
      'src/i18n/ui/pl.ts:283 (careers: bartenders work midweek "w godzinach The Cork", hours not given)',
      'docs/B2B.md:78 (open question: whether The Cork hours affect midweek availability)',
    ],
  },
  CAPACITY: {
    id: 'CAPACITY',
    kind: 'missing',
    what: 'How many guests SiSi holds on a club night. The only figures are corporate: 663 m2, The Cork seats 150, standing buffet 500, 2 screens.',
    why: 'A guest with a large group cannot tell if it fits, and cannot judge how full the night will be.',
    where: 'Reservations page, FAQ, corporate page (per-space capacity).',
    owner: 'Ignacy. Take the number from the venue\'s permit, not from the marketing figure.',
    placeholder: '[CAPACITY?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: [
      'src/data/site.ts:117-124 (VENUE_FACTS; the comment says the 150 is The Cork, not SiSi)',
      'docs/B2B.md:73 (room layouts and capacities per space still requested)',
    ],
  },
  TABLE_MINIMUM: {
    id: 'TABLE_MINIMUM',
    kind: 'missing',
    what: 'Smallest and largest party a booking accepts, table sizes, and any minimum spend per table.',
    why: 'A guest booking for 2 or for 14 cannot tell if the booking will be accepted before paying.',
    where: 'Reservations page and the provider flow hand-off.',
    owner: 'Ignacy / the floor manager.',
    placeholder: '[MIN-SPEND?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/i18n/ui/pl.ts:324-339 (the reservation rules state a price per person and no party limits)'],
  },
  PARTY_PRICE: {
    id: 'PARTY_PRICE',
    kind: 'missing',
    what:
      'The all-in price for a table of N beyond the two stated rules (100 zł per person, plus 40 zł per person on Saturday). "Special packages at promotional prices" and "prices may change during special events" have no figures.',
    why: 'A guest budgeting for a group cannot know the cost of a package or of an event night.',
    where: 'Reservations page, menu page call to action, event pages.',
    owner: 'Ignacy.',
    placeholder: '[PACKAGE-PRICE?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/i18n/ui/pl.ts:335 (packages, no price)', 'src/i18n/ui/pl.ts:339 (prices may change at special events)'],
  },
  ENTRANCE: {
    id: 'ENTRANCE',
    kind: 'missing',
    what: 'How to find the door inside the R32 complex: which entrance, where the queue forms, whether there is a bell or a doorman.',
    why: 'A first-time guest arriving in the 22:00-23:00 window may not find the club entrance from the street address alone.',
    where: 'Contact page, reservations page, the confirmation the provider sends.',
    owner: 'Ignacy / the door manager.',
    placeholder: '[ENTRANCE?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/data/site.ts:83 (the address is the only location text)', 'src/i18n/ui/pl.ts:167 (SiSi and The Cork share the R32 complex)'],
  },
  STEP_FREE: {
    id: 'STEP_FREE',
    kind: 'missing',
    what: 'Step-free access, lifts, accessible toilets.',
    why: 'A guest who uses a wheelchair or pushes a pram cannot tell if they can get in.',
    where: 'Contact page, reservations page, structured data (accessibility fields).',
    owner: 'Ignacy.',
    placeholder: '[ACCESS?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['docs/B2B.md:74 (listed as still requested from the venue team)'],
  },
  PARKING: {
    id: 'PARKING',
    kind: 'missing',
    what: 'Where to park near Rzeźnicza 32-33, and what it costs.',
    why: 'A guest arriving by car cannot plan the last stretch.',
    where: 'Contact page.',
    owner: 'Ignacy.',
    placeholder: '[PARKING?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['docs/B2B.md:75'],
  },
  TRANSPORT: {
    id: 'TRANSPORT',
    kind: 'missing',
    what: 'Public transport and taxi guidance, including how to get home after 04:00.',
    why: 'A guest leaving at closing cannot plan the trip home.',
    where: 'Contact page.',
    owner: 'Ignacy.',
    placeholder: '[TRANSPORT?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['docs/B2B.md:75'],
  },
  COORDINATES: {
    id: 'COORDINATES',
    kind: 'missing',
    what:
      'Coordinates checked independently. The code says the point is a building point "verified against the public address record on 2026-07-16"; it does not name the record and the point is not the entrance.',
    why: 'A navigation app or a map pin may put a guest at the wrong side of the R32 block.',
    where: 'Contact page map, NightClub and EventVenue geo in JSON-LD.',
    owner: 'Ignacy: confirm the entrance point on site.',
    placeholder: '[GEO?]',
    status: 'PENDING',
    basis: 'Assumption',
    evidence: ['src/data/site.ts:138-141'],
  },
  CHIVAS_ZONE: {
    id: 'CHIVAS_ZONE',
    kind: 'missing',
    what:
      'What the "Chivas Regal Zone" is. The home page has a full-bleed image with the title and no text: no description, offer, hours or terms.',
    why: 'A guest sees a brand banner and cannot tell what they can do or buy there.',
    where: 'Home page section between the events strip and the reservations block.',
    owner:
      'Ignacy. Any alcohol-brand promotion, sponsorship wording or brand-linked claim is a question for Ignacy and a lawyer; it is not judged here.',
    placeholder: '[CHIVAS-ZONE?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/components/home/Chivas.astro:2 (comment: "Branded sponsor banner")', 'src/components/home/Chivas.astro:14', 'src/i18n/ui/pl.ts:189'],
  },
  PHOTO_RIGHTS: {
    id: 'PHOTO_RIGHTS',
    kind: 'missing',
    what: 'Who took each photograph and film on the site, and the licence or usage right.',
    why: 'The team cannot reuse, crop or promote the images (or let a partner use them) without knowing who holds the rights.',
    where: 'public/framerusercontent.com/, public/video/, event banners, the Open Graph image.',
    owner: 'Ignacy (photographers, the previous agency that built the Framer site).',
    placeholder: '[PHOTO-RIGHTS?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['docs/B2B.md:68 (professional photographs with usage rights are still requested)', 'src/layouts/Base.astro:58-64 (the default social image is a Framer CDN URL)'],
  },
  PRESS: {
    id: 'PRESS',
    kind: 'missing',
    what: 'Real press mentions: outlet, title, date, link.',
    why: 'A first-time guest looks for outside proof that the place is what it says it is.',
    where: 'Home page, about section.',
    owner: 'Ignacy. Real ones only; the site has none and none may be invented.',
    placeholder: '[PRESS?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/data/site.ts:81-95 (no press link among the contact and social links)'],
  },
  REVIEWS: {
    id: 'REVIEWS',
    kind: 'missing',
    what: 'Real guest reviews or ratings. A Tripadvisor listing link exists; no review text or rating is shown.',
    why: 'A first-time guest looks for what other guests say.',
    where: 'Home page, about section, structured data (aggregateRating only if real and current).',
    owner: 'Ignacy. Quote or embed only reviews that exist, with their source and date.',
    placeholder: '[REVIEWS?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/data/site.ts:93-94 (Tripadvisor URL)', 'src/components/Footer.astro:58 (icon link only)'],
  },
  AGE_NOTICE: {
    id: 'AGE_NOTICE',
    kind: 'missing',
    what: 'An age notice: the minimum age to enter and to be served, and its exact wording in five languages.',
    why: 'A guest bringing a younger friend cannot tell if they will be turned away, and a refund on denial is only promised for denied entry.',
    where: 'Reservations page, terms (regulamin), event pages, footer.',
    owner: 'Ignacy, with a lawyer for the wording. The build blocks unverified age claims on purpose.',
    placeholder: '[AGE-NOTICE?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/lib/claims.mjs:13-20 (age claims are blocked until verified)', 'src/i18n/legal.ts:32 (terms only say staff may ask for ID)'],
  },
  PREPAYMENT_TERM: {
    id: 'PREPAYMENT_TERM',
    kind: 'missing',
    what:
      'The word that names the payment: przedpłata, zadatek, zaliczka or deposit. The club pages say "koszt rezerwacji" and "przedpłata"; the private-events pages say "zaliczka"; a blog post explains that zadatek and zaliczka have different legal effects. Which one applies to the table reservation is not stated.',
    why: 'A guest deciding whether to pay cannot tell what happens to the money if they cancel.',
    where: 'Reservations page, terms, provider flow, blog post on reservation costs.',
    owner: 'Ignacy and a lawyer. Wording only after they decide.',
    placeholder: '[PREPAYMENT-TERM?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: [
      'src/i18n/ui/pl.ts:325 ("koszt rezerwacji")',
      'src/i18n/ui/pl.ts:337 ("przedpłata")',
      'src/i18n/ui/pl.ts:392 ("zaliczka", private events)',
      'src/i18n/legal.ts:43',
    ],
  },
  REFUND_RULES: {
    id: 'REFUND_RULES',
    kind: 'missing',
    what:
      'When the paid amount is refunded. The reservations page promises a refund only if staff deny entry. Cancellation, no-show, late cancellation and date changes are not covered anywhere, and the terms (regulamin) have no refund clause at all.',
    why: 'A guest whose plans change cannot tell if they lose the money.',
    where: 'Reservations page, terms (regulamin), the provider flow.',
    owner: 'Ignacy and a lawyer.',
    placeholder: '[REFUND-RULES?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/i18n/ui/pl.ts:330 (refund on denied entry)', 'src/i18n/legal.ts:38-47 (the reservation clause has no refund rule)'],
  },
  CS_BOOKING: {
    id: 'CS_BOOKING',
    kind: 'missing',
    what: 'A Czech booking flow. The provider\'s /cs route renders English, so Czech guests open the Polish flow.',
    why: 'A Czech-speaking guest pays inside a flow in a language they may not read.',
    where: 'Every Czech page with a booking button; the reservations page note.',
    owner: 'Ignacy, with the reservation provider.',
    placeholder: '[CS-BOOKING?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/data/site.ts:20-22', 'src/i18n/ui/cs.ts:315 (the note says the system opens in Polish)'],
    notes:
      'The note on the Czech reservations page says the flow opens in Polish. The comment in site.ts says the provider\'s own /cs route renders English. Both are true of different paths; the site links the Polish one.',
  },
  LEGAL_TRANSLATIONS: {
    id: 'LEGAL_TRANSLATIONS',
    kind: 'missing',
    what: 'German, Italian and Czech versions of the terms, privacy policy and cookie policy. Those locales show the English text with a banner; the Polish version is the binding one.',
    why: 'A guest reading the rules in their own language gets English, on the very page that sets the entry and refund rules.',
    where: 'The terms, privacy and cookie pages in de, it, cs.',
    owner: 'Ignacy, with a professional legal translator.',
    placeholder: '[LEGAL-DE/IT/CS?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: [
      'src/i18n/legal.ts:11-12 (TODO for professional translations)',
      'src/i18n/legal.ts:425-429 (fallback returns the English text)',
      'docs/I18N.md:67-68 (says the fallback is Polish; the code and the build show English)',
    ],
    notes: 'The dist pages for de, it, cs terms show English text (dist/de/agb/index.html). docs/I18N.md and RESEARCH.md say Polish: stale.',
  },
  DRESS_CODE_DETAIL: {
    id: 'DRESS_CODE_DETAIL',
    kind: 'missing',
    what: 'What "smart casual" means at the door and what is refused.',
    why: 'A guest deciding what to wear cannot tell if trainers or a cap will be refused.',
    where: 'Reservations page, terms.',
    owner: 'Ignacy / the door manager.',
    placeholder: '[DRESS-CODE?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/i18n/ui/pl.ts:330', 'src/i18n/legal.ts:34'],
  },
  CLOAKROOM: {
    id: 'CLOAKROOM',
    kind: 'missing',
    what: 'Whether there is a cloakroom on club nights, its price and where it is. The corporate page lists a cloakroom service; the terms mention items "handed to the cloakroom".',
    why: 'A guest arriving with a coat in winter cannot plan.',
    where: 'Reservations page, terms.',
    owner: 'Ignacy.',
    placeholder: '[CLOAKROOM?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/i18n/ui/pl.ts:456', 'src/i18n/legal.ts:60'],
  },
  PAYMENT_METHODS: {
    id: 'PAYMENT_METHODS',
    kind: 'missing',
    what: 'What payment is accepted at the bar and door (card, cash, BLIK). Structured data says only that the currency is PLN.',
    why: 'A guest cannot tell if they need cash for the door.',
    where: 'Reservations page, FAQ, structured data (paymentAccepted).',
    owner: 'Ignacy.',
    placeholder: '[PAYMENT?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/data/site.ts:227 (currenciesAccepted only)'],
  },
  CONTACT_HOURS: {
    id: 'CONTACT_HOURS',
    kind: 'missing',
    what: 'When the reservations phone and the e-mail are answered.',
    why: 'A guest with a last-minute question does not know when to call.',
    where: 'Contact page, reservations page.',
    owner: 'Ignacy.',
    placeholder: '[CONTACT-HOURS?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/data/site.ts:81-90'],
  },
  MENU_VERIFIED: {
    id: 'MENU_VERIFIED',
    kind: 'missing',
    what: 'The date the menu prices were last checked against the bar, and by whom.',
    why: 'A guest budgeting for the night cannot tell if the prices are current.',
    where: 'Menu page ("prices as of"), structured data.',
    owner: 'The bar manager, then Ignacy.',
    placeholder: '[MENU-DATE?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['docs/superpowers/specs/2026-07-15-menu-availability-and-volume-corrections-design.md:1-3 (the last recorded manual correction, 2026-07-15)'],
  },
  SATURDAY_ENTRY_CONFLICT: {
    id: 'SATURDAY_ENTRY_CONFLICT',
    kind: 'decision',
    what:
      'Saturday entry per person is 40 zł on the reservations page, home page, llms.txt and four blog posts (all five languages), and 30 zł in the terms (regulamin, pl and en, shown in de, it, cs as English).',
    why: 'A guest who reads the terms budgets 30 zł and is asked 40 zł.',
    where: 'Terms page in all five languages.',
    owner: 'Ignacy: say which number is right.',
    placeholder: '[SAT-ENTRY?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: [
      'src/i18n/ui/pl.ts:327 (40 zł)',
      'src/i18n/legal.ts:42 (30 zł, Polish terms)',
      'src/i18n/legal.ts:241 (30, English terms)',
    ],
    notes: 'venue.ts holds 40 (the value in the Phase 3a brief and in the dictionaries) and lists 30 under `contradictedBy`. Neither is treated as settled.',
  },
  ARRIVAL_WINDOW_CONFLICT: {
    id: 'ARRIVAL_WINDOW_CONFLICT',
    kind: 'decision',
    what: 'The arrival window ends at 23:00 on the reservations page in all five languages, and at 23:30 in the terms (pl and en).',
    why: 'A guest arriving at 23:15 is on time by one page and late by the other.',
    where: 'Terms page in all five languages.',
    owner: 'Ignacy: say which time is right.',
    placeholder: '[ARRIVAL?]',
    status: 'PENDING',
    basis: 'Confirmed',
    evidence: ['src/i18n/ui/pl.ts:328 (22:00-23:00)', 'src/i18n/legal.ts:44 (22:00-23:30, Polish terms)', 'src/i18n/legal.ts:243 (22:00 and 23:30, English terms)'],
    notes: 'venue.ts holds 23:00 (the brief and the dictionaries) and lists 23:30 under `contradictedBy`.',
  },
};
