// GENERATED by scripts/sync-articles.mjs from the BabyLoveGrowth articles
// API. Do not edit by hand - the next sync overwrites it.
import type { ArticleItem } from './articles';

export const GENERATED_ARTICLES: ArticleItem[] = [];
