// GENERATED by scripts/sync-events.mjs from the "Wydarzenia" Google Drive
// folder (Banery + Opisy). Do not edit by hand - the next sync overwrites it.
import type { EventItem } from './site';

export const GENERATED_EVENTS: EventItem[] = [
  {
    "title": "Friday at SiSi",
    "start": "2026-06-26T22:00:00+02:00",
    "note": "DJ ADB",
    "img": "/events/2026-06-26-friday-at-sisi.webp",
    "price": 0,
    "description": "Krótki opis wydarzenia",
    "genres": [
      "House",
      "Pop",
      "Funk"
    ]
  }
];
