// GENERATED by scripts/sync-events.mjs from the "Wydarzenia" Google Drive
// folder (Banery + Opisy). Do not edit by hand - the next sync overwrites it.
import type { EventItem } from './site';

export const GENERATED_EVENTS: EventItem[] = [];
